### ISSUE TITLE
Python type hint: NameError: name '...' is not defined

### ISSUE THREAD

**Issue by kingspp** [agronholm/sphinx-autodoc-typehints#14] opened 2017-01-21 15:07 UTC
**Usecase:**
```python
class Foo(object):
    def __init__(self):
        pass
    
    def get_foo(self, name:str) -> 'Foo' :
        return self
```

The above is a simple example of the issue I am facing. Python type hints supports ' ' to be used when the class is not defined and will be defined at a later stage. Sphinx documentation using your extension fails because Foo is not defined. 

**Note:**  I have also tried adding a `__main__` method, thinking it might stop auto-execution, but I ended up having the same error. 

 [Stacktrace](http://pastebin.com/x0Ja4Wbx)

**Comment by agronholm** [comment] 2017-01-21 15:10
The extension uses `typing.get_type_hints()` to resolve such references automatically, making me wonder how you ended up with an error here.

As an aside, the name `__main__` is not special among method names. Where did you find documentation that said it was?

**Comment by kingspp** [comment] 2017-01-21 15:14
I read in sphinx quick start docs, where they stated to use `__main__` method to avoid execution of the script

**Comment by agronholm** [comment] 2017-01-21 15:15
I think I misunderstood what you were trying to say. Can you show me your real code? This looks artificial and I can't see how it would possibly fail.

**Comment by agronholm** [comment] 2017-01-21 15:16
By the way, you don't need to explicitly inherit classes from `object` on Python 3.

**Comment by kingspp** [comment] 2017-01-21 15:21
I have updated the issue with Stack Trace. Can you pls check it?

**Comment by agronholm** [comment] 2017-01-21 15:22
And the above code represents the module *exactly*? Because the error says there is no class named "Foo".

**Comment by kingspp** [comment] 2017-01-21 15:29
Usecase

```python
class ConcatOperator(Operator):
    @strict_type
    def __init__(self, ...):
        super().__init__(name=name)
        pass

    @strict_type
    def create_operator(self, model_name:str, operator_id:int) -> 'ConcatOperator':
        self.model_name = model_name
        self.operator_id = operator_id
        self.validate()
        return self

    def validate(self):
        pass
```

**Comment by kingspp** [comment] 2017-01-21 15:34
The error is caused by the use of decorator. If I remove `@strict_type`, the extension works flawlessly. Any ideas why it is checking-in decorator? I have used `wraps(f)` suggested by python to avoid clashes with the parameters of the decorator and the actual parameters of the function

```python
def strict_type(f):
    @wraps(f)
    def type_checker(*args, **kwargs):
        pass
    pass
```

**Comment by agronholm** [comment] 2017-01-21 15:35
Your decorator returns `None` so the class is removed from the module and is replaced with `None`.

What did you intend your decorator to do?

**Comment by agronholm** [comment] 2017-01-21 15:44
I mean, your method, not your class, gets replaced with `None`.

Anyway, if you wanted to implement a type checker, why not just use [typeguard](https://pypi.org/project/typeguard/) instead?

**Comment by kingspp** [comment] 2017-01-21 15:50
Thnx for the reply. Yes I was trying to implement strict typing for a library. I will test the same case with typeguard and let you know if I face the same issue.

**Comment by agronholm** [comment] 2017-01-21 16:16
On second thought, this may be a fixable problem, caused by the use of any wrapping decorator.

**Comment by agronholm** [comment] 2017-01-28 23:16
Well...it is a fixable problem but it needs to be fixed in Sphinx's autodoc itself.
The offending code is in `autodoc.py`, lines 370-371:
```python
    introspected_hints = (typing.get_type_hints(function)
                          if typing and hasattr(function, '__code__') else {})
```
This fails because the global namespace of the wrapper does not contain the globals from the original function. What is needed is to call `get_type_hints(obj, original.__globals__)` where `original` is the unwrapped function.

**Comment by agronholm** [comment] 2017-01-28 23:16
Or actually, just unwrapping it first would be adequate.

**Comment by agronholm** [comment] 2017-01-28 23:28
This change I committed still requires the proper fix in autodoc.py.

**Closed** 2017-01-28 23:27 UTC

**Comment by GedeonGg** [comment] 2018-07-11 11:17
hey Guys! i have a problem but which is kind of related to the above question... well i have defined a function in my class.py and i want to call that function in a field so that it can be executed but if i do so it gives me a NameError 'myfunction()' is not defined please anyone help i am new in this.

**Comment by agronholm** [comment] 2018-07-11 14:47
What prompted you to ask your question here? This is the bug tracker for sphinx-autodoc-typehints and it doesn't seem like your question is related.
