### ISSUE TITLE
Compatibility with Sphinx.ext.napoleon 

### ISSUE THREAD

**Issue by tommyip** [agronholm/sphinx-autodoc-typehints#15] opened 2017-03-29 16:56 UTC
Napoleon is a Sphinx extension which allow the use of Google / Numpy style docstrings. Currently, it doesn't work well with this extension, it can only strip the type hint from function definition and add the return type.
Is it possible to make it inject the type hint to the argument list in the docs?

**Comment by agronholm** [comment] 2017-03-29 21:20
Personally I have no interest in support Google/Numpy style docstrings. I don't even know what it would take to do what you want. Would you like to share an example?

**Comment by wheerd** [comment] 2017-03-30 14:44
There is already a fork for that: [sphinx-autodoc-napoleon-typehints](https://github.com/daviskirk/sphinx-autodoc-napoleon-typehints)

**Comment by agronholm** [comment] 2017-03-30 18:17
Ok, sounds like I can close this issue then.

**Comment by evanunderscore** [comment] 2017-04-30 10:39
I've only just looked at this, but it appears that this works perfectly fine with Napoleon, provided that you put `sphinx_autodoc_typehints` *after* `sphinx.ext.napoleon`. If I put this first, I get the problem @tommyip describes. A note in the readme saying Napoleon is supported with this caveat should be sufficient to fix the problem.

**Comment by agronholm** [comment] 2017-04-30 12:39
That much I can do :)

**Comment by evanunderscore** [comment] 2017-05-01 11:43
Thanks! Also since I've noticed I didn't actually specify - the ordering I'm talking about is the `extensions` list in `conf.py`.

**Comment by agronholm** [comment] 2017-05-01 23:37
Yes, I understood.

**Closed** 2017-05-14 19:21 UTC

**Comment by kylebarron** [comment] 2018-07-09 16:33
For anyone else trying to get this to work with Napoleon, for me, this only works with the napoleon setting:
```
napoleon_use_param = True
```

Otherwise the type hints are removed from the function signature but not added to the docstring.

**Comment by cmichelenstrofer** [comment] 2022-07-20 20:14
> For anyone else trying to get this to work with Napoleon, for me, this only works with the napoleon setting:
> 
> ```
> napoleon_use_param = True
> ```
> 
> Otherwise the type hints are removed from the function signature but not added to the docstring.

I am using this and the type hints are still removed :(

**Comment by jgarte** [comment] 2022-12-22 08:06
@cmichelenstrofer Is this still a problem for you?

**Comment by cmichelenstrofer** [comment] 2022-12-22 16:13
@jgarte Ahh, I forget how I solved it but I was able to work around this issue and get the desired behavior. So it's all good. I'm about to go on vacation or I would have looked into it more :) But here is the relevant [`conf.py`](https://github.com/SNL-WaterPower/WecOptTool/blob/main/docs/source/conf.py) file and the [output documentation](https://snl-waterpower.github.io/WecOptTool/api_docs/wecopttool.html) in case you are curious.

**Comment by jstet** [comment] 2023-05-10 22:39
@cmichelenstrofer would you be so kind to post your workaround again?

**Comment by cmichelenstrofer** [comment] 2023-05-10 22:45
The files still exist, the issue is that the organization name in GitHub changed. Here are the correct links: 
* `conf.py`: https://github.com/sandialabs/WecOptTool/blob/main/docs/source/conf.py
* `documentation`: https://sandialabs.github.io/WecOptTool/api_docs/wecopttool.html

**Comment by cmichelenstrofer** [comment] 2023-05-10 22:48
> @cmichelenstrofer would you be so kind to post your workaround again?

@jstet 
The files still exist, the issue is that the organization name in GitHub changed. I just updated the links above.

**Comment by MLopez-Ibanez** [comment] 2024-08-19 21:12
> For anyone else trying to get this to work with Napoleon, for me, this only works with the napoleon setting:
> 
> ```
> napoleon_use_param = True
> ```
> 
> Otherwise the type hints are removed from the function signature but not added to the docstring.

The `README.md` should mention this!

**Comment by gaborbernat** [comment] 2024-08-19 21:18
PR welcome.
