### ISSUE TITLE
Cannot resolve forward reference

### ISSUE THREAD

**Issue by revmischa** [agronholm/sphinx-autodoc-typehints#93] opened 2019-08-20 11:46 UTC
Code:
```
if TYPE_CHECKING:
    from qc.model.user import User

...

    @property
    @abstractmethod
    def owner(self) -> "User":
        ...
```

Error with `set_type_checking_flag = False`:
```
WARNING: Cannot resolve forward reference in type annotations of "qc.db.Owned.owner": name 'User' is not defined                                                                                             

Exception occurred:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 786, in findsource                                                                                                 
    raise OSError('could not get source code')
OSError: could not get source code
```

Error with `set_type_checking_flag = True`:
```
WARNING: autodoc: failed to import module 'app' from module 'qc'; the following exception was raised:
cannot import name 'User' from 'qc.model.user' (/Users/cyber/dev/jb/qc/qc-backend/qc/model/user.py)
WARNING: autodoc: failed to import module 'commands' from module 'qc'; the following exception was raised:
cannot import name 'TSTZ' from 'qc.db' (/Users/cyber/dev/jb/qc/qc-backend/qc/db/__init__.py)
... [many more]
cannot import name 'User' from 'qc.model.user' (/Users/cyber/dev/jb/qc/qc-backend/qc/model/user.py)
cannot import name 'User' from 'qc.model.user' (/Users/cyber/dev/jb/qc/qc-backend/qc/model/user.py)
cannot import name 'User' from 'qc.model.user' (/Users/cyber/dev/jb/qc/qc-backend/qc/model/user.py)
WARNING: autodoc: failed to import module 'test' from module 'qc'; the following exception was raised:
cannot import name 'User' from 'qc.model.user' (/Users/cyber/dev/jb/qc/qc-backend/qc/model/user.py)
```

Using `sphinx-apidoc` and python 3.7.

**Comment by agronholm** [comment] 2019-08-21 06:51
Duplicate of #72. See the discussion over there. Typeguard must be able to evaluate the expression in the annotation.

**Closed by agronholm** 2019-08-21 06:51 UTC
Labels: duplicate

**Comment by revmischa** [comment] 2019-08-21 06:56
Type checking seems to work normally; `mypy` runs without any problem. I am importing the module using `TYPE_CHECKING`. The expression should be evaluatable if `TYPE_CHECKING` is enabled. Reading #72, I'm unclear how to fix this.

**Comment by revmischa** [comment] 2019-08-21 07:01
The forward references are circular, of course, that's why they have the `if TYPE_CHECKING` guard. It seems like with sphinx this feature of type checking does not work like it does in mypy.
If I remove this particular circular reference entirely I get:
```
reading sources... [ 81%] source/qc.model                                                             
Exception occurred:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
The full traceback has been saved in /var/folders/n8/rmzyc9yx2zvbc978_p6y_by40000gn/T/sphinx-err-p5nylmyb.log, if you
 want to report the issue to the developers.                                                                        
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2


```
# Sphinx version: 2.2.0
# Python version: 3.7.1 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.1
# Last messages:
#   reading sources... [ 45%] source/qc.api.fee_compliance
#   
#   reading sources... [ 54%] source/qc.api.logs
#   
#   reading sources... [ 63%] source/qc.api.user
#   
#   reading sources... [ 72%] source/qc.db
#   
#   reading sources... [ 81%] source/qc.model
#   
# Loaded extensions:
#   sphinx.ext.mathjax (2.2.0) from /Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (2.2.0) from /Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.viewcode (2.2.0) from /Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/ext/viewcode.py
#   sphinx_autodoc_typehints (unknown version) from /Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx_autodoc_typehints.py
Traceback (most recent call last):
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/application.py", line 346, in build
    self.builder.build_update()
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/io.py", line 326, in read_doc
    pub.publish()
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/io.py", line 114, in read
    self.parse()
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/parsers.py", line 95, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2344, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2356, in explicit_construct
    return method(self, expmatch)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2099, in directive
    directive_class, match, type_name, option_presets)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2148, in run_directive
    result = directive_instance.run()
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/ext/autodoc/directive.py", line 146, in run
    documenter.generate(more_content=self.content)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 732, in generate
    self.document_members(all_members)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 654, in document_members
    check_module=members_check_module and not isattr)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 1188, in generate
    all_members=all_members)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 729, in generate
    self.add_content(more_content)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 1172, in add_content
    super().add_content(more_content)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 471, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 441, in process_doc
    self.options, docstringlines)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/application.py", line 450, in emit
    return self.events.emit(event, *args)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx/events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 303, in process_docstring
    type_hints = get_all_type_hints(obj, name)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 205, in get_all_type_hints
    rv = backfill_type_hints(obj, name)
  File "/Users/cyber/.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 243, in backfill_type_hints
    obj_ast = ast.parse(textwrap.dedent(inspect.getsource(obj)))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 973, in getsource
    lines, lnum = getsourcelines(object)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
```

**Comment by agronholm** [comment] 2019-08-21 07:35
Mypy does static analysis of the code while Sphinx does not. It relies on having the information available at run time. Have you read the README? The `set_type_checking_flag` should solve your problem.

**Comment by revmischa** [comment] 2019-08-21 07:48
I did read the README. I tried setting the flag. I reported the effects of it being on and off in the initial post above.

**Comment by agronholm** [comment] 2019-08-21 07:52
Yeah, sorry I missed that. But like I explained, the information needs to be available at run time. Therefore the only way to avoid the circular import problem is the one laid out in the README. There is no other way to avoid the import error when `TYPE_CHECKING` is set to `True`.

**Comment by revmischa** [comment] 2019-08-21 09:50
Okay but I am still getting an error even if I remove the circular reference entirely, see above

**Comment by agronholm** [comment] 2019-08-21 09:51
Can you provide me a means to reproduce this issue locally?

**Comment by revmischa** [comment] 2019-08-21 10:22
Certainly - 
In the [sphinx branch](https://github.com/jetbridge/sls-flask/compare/sphinx?expand=1)
`cd doc`
`make html`


This is the output I get:
```
(slsflask) doc|sphinx⚡ ⇒ make html
sphinx-apidoc ../TEMPLATE -f -o source
Creating file source/TEMPLATE.rst.
Creating file source/TEMPLATE.api.rst.
Creating file source/TEMPLATE.api.auth.rst.
Creating file source/TEMPLATE.db.rst.
Creating file source/TEMPLATE.model.rst.
Creating file source/TEMPLATE.test.rst.
Creating file source/modules.rst.
Running Sphinx v2.2.0
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 7 source files that are out of date
updating environment: [new config] 7 added, 0 changed, 0 removed
/Users/cyber/dev/jb/slsflask/doc/source/TEMPLATE.rst:7: WARNING: toctree contains reference to excluded document 'source/TEMPLATE.test'               

Exception occurred:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
The full traceback has been saved in /var/folders/n8/rmzyc9yx2zvbc978_p6y_by40000gn/T/sphinx-err-nbfaqfpp.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

**Comment by agronholm** [comment] 2019-08-21 11:06
This is all I get (once I installed the dependencies missing from Pipfile):
```
/tmp/sls-flask/doc/source/TEMPLATE.rst:7: WARNING: toctree contains reference to excluded document 'source/TEMPLATE.test'
WARNING: autodoc: failed to import module 'app' from module 'TEMPLATE'; the following exception was raised:
cannot import name 'TSTZ' from 'TEMPLATE.db' (/tmp/sls-flask/TEMPLATE/db/__init__.py)
WARNING: autodoc: failed to import module 'commands' from module 'TEMPLATE'; the following exception was raised:
cannot import name 'TSTZ' from 'TEMPLATE.db' (/tmp/sls-flask/TEMPLATE/db/__init__.py)
WARNING: autodoc: failed to import module 'create_app' from module 'TEMPLATE'; the following exception was raised:
cannot import name 'TSTZ' from 'TEMPLATE.db' (/tmp/sls-flask/TEMPLATE/db/__init__.py)
WARNING: autodoc: failed to import module 'monitor' from module 'TEMPLATE.api'; the following exception was raised:
cannot import name 'TSTZ' from 'TEMPLATE.db' (/tmp/sls-flask/TEMPLATE/db/__init__.py)
WARNING: autodoc: failed to import module 'auth.schema' from module 'TEMPLATE.api'; the following exception was raised:
cannot import name 'User' from 'TEMPLATE.model.user' (/tmp/sls-flask/TEMPLATE/model/user.py)
WARNING: autodoc: failed to import module 'auth' from module 'TEMPLATE.api'; the following exception was raised:
cannot import name 'User' from 'TEMPLATE.model.user' (/tmp/sls-flask/TEMPLATE/model/user.py)
WARNING: autodoc: failed to import module 'db.extid' from module 'TEMPLATE'; the following exception was raised:
cannot import name 'TSTZ' from 'TEMPLATE.db' (/tmp/sls-flask/TEMPLATE/db/__init__.py)
WARNING: autodoc: failed to import module 'db.fixtures' from module 'TEMPLATE'; the following exception was raised:
cannot import name 'TSTZ' from 'TEMPLATE.db' (/tmp/sls-flask/TEMPLATE/db/__init__.py)
WARNING: autodoc: failed to import module 'db' from module 'TEMPLATE'; the following exception was raised:
cannot import name 'TSTZ' from 'TEMPLATE.db' (/tmp/sls-flask/TEMPLATE/db/__init__.py)
WARNING: autodoc: failed to import module 'model.user' from module 'TEMPLATE'; the following exception was raised:
cannot import name 'User' from 'TEMPLATE.model.user' (/tmp/sls-flask/TEMPLATE/model/user.py)
WARNING: autodoc: failed to import module 'model' from module 'TEMPLATE'; the following exception was raised:
cannot import name 'User' from 'TEMPLATE.model.user' (/tmp/sls-flask/TEMPLATE/model/user.py)
```

**Comment by revmischa** [comment] 2019-08-21 11:12
I get something different! Weird.

I am using Pipenv for installing dependencies but it shouldn't make any difference
What was missing? It seems to build and run tests from scratch without issue: https://circleci.com/workflow-run/c5754f00-e835-405c-b9b6-4de41a4b8f72

**Comment by revmischa** [comment] 2019-08-21 11:12
Does this help? https://github.com/jetbridge/sls-flask/commit/82120921553475238c7434cc537cdf3588aa4fcf

**Comment by agronholm** [comment] 2019-08-21 11:19
I haven't used pipenv much so I didn't realize you needed to do `pipenv install -d`. But I still get the same error.

**Comment by revmischa** [comment] 2019-08-21 11:21
How can we debug and fix that error you see? It's the same error as my initial error I reported here.
I think something else is broken as well because of the `OSError: could not get source code` but that's not the main issue.

**Comment by agronholm** [comment] 2019-08-21 11:27
Nevermind, with your latest commit I now get the `could not get source code` error.

**Comment by agronholm** [comment] 2019-08-21 11:45
The problem occurs because the documentation explicitly selects undocumented members to be listed and then the extension gets a slot wrapper for `object.__init__` which it cannot process properly. I've seen something like this before but never associated it with this particular error.

**Comment by revmischa** [comment] 2019-08-22 07:56
What can I do?
My main problem is related to that `cannot import name 'User' from 'qc.model.user'` issue - I don't know how to solve it as the error message doesn't give me enough info to track it down. Mypy runs fine.

**Comment by agronholm** [comment] 2019-08-22 09:37
Did you try following the instructions in the README about only importing modules and not things directly from them? So instead of `from qc.model.user import User` do `from qc.model import user` and then use `user.User`?

**Comment by revmischa** [comment] 2019-08-22 10:29
Yes. Right now getting the `OSError: could not get source code` error

**Comment by agronholm** [comment] 2019-08-22 10:30
Yes, but that is a problem which is not related to the circular import issues.

**Comment by revmischa** [comment] 2019-08-22 13:01
Is there something I can do/try to fix it?

**Comment by agronholm** [comment] 2019-08-22 13:29
I'm not entirely sure what the proper fix is. Perhaps any object without a `__module__` attribute should be ignored?

**Comment by revmischa** [comment] 2019-08-22 13:37
I have no idea sorry, I've never used Sphinx before in my life. I was just hoping to run sphinx-apidoc and have it make use of my type annotations.

**Comment by revmischa** [comment] 2019-09-04 13:34
Any way to move forward on this? Or reopen?

**Comment by agronholm** [comment] 2019-09-04 18:43
Is the issue, as reported in the subject, still relevant? Or do you need to open a new ticket for a different problem?

**Comment by revmischa** [comment] 2019-09-04 18:49
Yes the original post is still the issue at hand. `OSError: could not get source code`

**Comment by revmischa** [comment] 2019-09-04 18:53
I get either that or the other error, where it says it can't import some module. I assume it is because of circular imports but it's really hard to track down where the issue is. I am importing packages when `TYPE_CHECKING`, not the actual name itself, as it says in the readme.

**Comment by agronholm** [comment] 2019-09-04 20:20
I would like to understand better what `obj` is when `inspect.getsource(obj)` fails to get its source code.
