### ISSUE TITLE
Apparent incompatibility with slot wrappers

### ISSUE THREAD

**Issue by gdude2002** [agronholm/sphinx-autodoc-typehints#12] opened 2017-01-01 11:37 UTC
Here's a traceback for you. I've found this error appears on any class that doesn't explicitly define an `__init__()` - which means that the `__init__` in its dict refers to a C method wrapper.

Python 3.6.

```
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\sphinx\cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "C:\Python36\lib\site-packages\sphinx\application.py", line 333, in build
    self.builder.build_update()
  File "C:\Python36\lib\site-packages\sphinx\builders\__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "C:\Python36\lib\site-packages\sphinx\builders\__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "C:\Python36\lib\site-packages\sphinx\environment\__init__.py", line 556, in update
    self._read_serial(docnames, app)
  File "C:\Python36\lib\site-packages\sphinx\environment\__init__.py", line 576, in _read_serial
    self.read_doc(docname, app)
  File "C:\Python36\lib\site-packages\sphinx\environment\__init__.py", line 684, in read_doc
    pub.publish()
  File "C:\Python36\lib\site-packages\docutils\core.py", line 217, in publish
    self.settings)
  File "C:\Python36\lib\site-packages\sphinx\io.py", line 55, in read
    self.parse()
  File "C:\Python36\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    input_source=document['source'])
  File "C:\Python36\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "C:\Python36\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Python36\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "C:\Python36\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 2318, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 2122, in run_directive
    result = directive_instance.run()
  File "C:\Python36\lib\site-packages\sphinx\ext\autodoc.py", line 1647, in run
    documenter.generate(more_content=self.content)
  File "C:\Python36\lib\site-packages\sphinx\ext\autodoc.py", line 992, in generate
    self.document_members(all_members)
  File "C:\Python36\lib\site-packages\sphinx\ext\autodoc.py", line 914, in document_members
    check_module=members_check_module and not isattr)
  File "C:\Python36\lib\site-packages\sphinx\ext\autodoc.py", line 989, in generate
    self.add_content(more_content)
  File "C:\Python36\lib\site-packages\sphinx\ext\autodoc.py", line 1362, in add_content
    ModuleLevelDocumenter.add_content(self, more_content)
  File "C:\Python36\lib\site-packages\sphinx\ext\autodoc.py", line 723, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "C:\Python36\lib\site-packages\sphinx\ext\autodoc.py", line 685, in process_doc
    self.options, docstringlines)
  File "C:\Python36\lib\site-packages\sphinx\application.py", line 589, in emit
    results.append(callback(self, *args))
  File "C:\Python36\lib\site-packages\sphinx_autodoc_typehints.py", line 68, in process_docstring
    type_hints = get_type_hints(obj)
  File "C:\Python36\lib\typing.py", line 1419, in get_type_hints
    'or function.'.format(obj))
TypeError: <slot wrapper '__init__' of 'object' objects> is not a module, class, method, or function.
```

**Comment by AlexandreDecan** [comment] 2017-01-12 09:21
I recently ran into this issue. 
Is there any workaround?

**Comment by agronholm** [comment] 2017-01-12 09:25
This needs to be fixed properly and I have this underway. I've just been swamped with my real work. I intend to have this working in the next three weeks.

**Comment by AlexandreDecan** [comment] 2017-01-12 09:33
Thank you!

**Comment by gdude2002** [comment] 2017-01-12 14:39
Thanks, I look forward to seeing the fix!

**Comment by travcunn** [comment] 2017-01-25 21:01
We are also seeing this issue in Python 3.5.3.

Also, not sure if related, but `typing` in the standard library was recently updated.

**Comment by agronholm** [comment] 2017-01-25 21:03
It's bothersome that Python introduces breaking changes in micro updates, but this is not the first time. I've been so badly swamped with work for the last few weeks that I haven't gotten around to doing much with F/OSS projects, but this is one of my highest priorities when I get some free time.

**Comment by AlexandreDecan** [comment] 2017-01-26 08:38
Maybe one should open an issue on https://github.com/python/typing/ to inform them they introduced such a backward incompatible change?

**Comment by agronholm** [comment] 2017-01-26 09:59
The `typing` module was provisional in 3.5 so all bets were off regarding backwards compatibility. No point in complaining.

**Comment by AlexandreDecan** [comment] 2017-01-26 10:01
Yeah, you're right. 

Is there any way we can help you on this issue? 
I don't see any test suite in the repository, do you have one?

**Comment by wheerd** [comment] 2017-01-26 10:07
They mainly fixed a lot of bugs for 3.5 and you can finally use code with type hints in both 3.6 and 3.5 without breaking things.

This issue can easily be fixed by checking that an object is not a `slot_wrapper` before calling `get_type_hints` even though I agree that this could be checked in that function as well (and there should probably be a type for it in the `types` module, too).

```python
slot_wrapper_type = type(object.__init__)
...
if not isinstance(obj, slot_wrapper_type):
    type_hints = get_type_hints(obj)
...
```

**Comment by agronholm** [comment] 2017-01-26 21:56
And what do you suggest to be done if it is a slot wrapper? Just ignore type hints?

**Comment by wheerd** [comment] 2017-01-26 22:19
Slot wrappers are only for methods builtin types like `object.__str__`. None of those builtin methods have type hints as far as I know. They have nothing to do `__slots__` as far as I know if that is what you were thinking about.

**Comment by agronholm** [comment] 2017-01-26 22:22
I may have mixed this up with another issue. I'm wondering if there are any other cases where `get_type_hints()` would fail in a similar manner.

**Comment by agronholm** [comment] 2017-03-19 12:29
This will now get more attention from me as it's blocking the release of my other project, Asphalt 3.0.

**Comment by gdude2002** [comment] 2017-03-21 14:24
That's great news - any chance of an ETA?

**Comment by agronholm** [comment] 2017-03-21 18:32
I will try to get an update released on the coming weekend.

**Comment by agronholm** [comment] 2017-03-25 22:20
The test suite now passes on 3.5.3 locally. Next I will fix the regressions introduced for 3.5.0.

**Comment by agronholm** [comment] 2017-03-25 23:48
Manual testing revealed that the exact reported issue had not actually been fixed.

**Closed** 2017-03-26 00:06 UTC
Labels: bug

**Comment by AlexandreDecan** [comment] 2017-03-26 08:15
Thank you for the fix. I see there's a tag "1.2.0" (which is indeed a working copy of sphinx-autodoc-typehints), but this version is not yet available on PyPi (which is wierd because your Travis-CI is configured to deploy the package on each tag).

**Comment by AlexandreDecan** [comment] 2017-03-26 08:18
Mmmh while your fix seems to work on Python 3.5, I still get weird issues with 3.4 or 3.6. 
See here for example:
https://travis-ci.org/AlexandreDecan/sismic/builds/215164501

**Comment by agronholm** [comment] 2017-03-26 11:18
According to your build log, the build crashed when `get_type_hints()` raised a TypeError. But sphinx-autodoc-typehints catches any TypeErrors raised by it so it cannot be the culprit here.

**Comment by agronholm** [comment] 2017-03-26 11:21
I've uploaded new wheels and hopefully fixed the Travis authentication issue.

**Comment by AlexandreDecan** [comment] 2017-03-26 14:55
Fixed, thanks!
