### ISSUE TITLE
typing.TextIO gets mangled

### ISSUE THREAD

**Issue by flying-sheep** [agronholm/sphinx-autodoc-typehints#96] opened 2019-08-21 15:38 UTC
We call `annotation_cls.__qualname__title()` to make e.g. `'tuple'` into `'Tuple'`, but this breaks `TextIO`, which becomes mangled into `'Textio'`.

**Comment by agronholm** [comment] 2019-09-07 16:40
This is actually a duplicate of #81.

**Closed by agronholm** 2019-09-07 16:40 UTC
Labels: duplicate
